### PR TITLE
Allow Laravel 5.1

### PR DESCRIPTION
**Pull request by dennisoderwald**

### CODE REVIEW

**Comment by dennisoderwald** [comment]
Closes #2.

**Comment by dennisoderwald** [comment]
Thanks @EvanDarwin. What is the version for composer?

**Comment by EvanDarwin** [comment]
The new release is **1.1.1**.

**Comment by dennisoderwald** [comment]
Not released yet? https://packagist.org/packages/evandarwin/laravel-jsend

**Comment by EvanDarwin** [comment]
I can't seem to get the release to show up in packagist, **1.1.1** and **1.1.2** are the same commit, and neither seem to be showing up in Packagist.

**Comment by EvanDarwin** [comment]
Ok, issue solved. **1.1.1** should now show up in Packagist.

**Comment by dennisoderwald** [comment]
Thanks @EvanDarwin! :) :+1:

**Pull request merged**
